#version 450

layout(binding = 0) uniform sampler2D background_img;
layout(binding = 1, rgba8) uniform image2D output_img;


layout(local_size_x = 8, local_size_y = 8) in;

void main()
{
    uvec2 wh = gl_NumWorkGroups.xy * gl_WorkGroupSize.xy;
    uvec2 xy = gl_GlobalInvocationID.xy;

    vec4 color = vec4(texture(background_img, vec2(xy) / vec2(wh)).rgb, 1.0);

    imageStore(output_img, ivec2(xy), color);
}
